version: "3.7"
services:
  ss14_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ss14
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
  ss14:
    depends_on:
      - ss14_db
    image: "ghcr.io/thetastation/ss14watchdog-dockerized:main"
    volumes:
      - ./appsettings.yml:/app/appsettings.yml
      - ./instances:/app/instances
    ports:
      - "${WATCHDOG_PORT}:5000"
      - "${GAME_PORT}:1212"
      - "${GAME_PORT}:1212/udp"

